# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.8
working_directory: ~/shopping-cart-tests
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - browser-tools/install-browser-tools
      # Checkout the code as the first step.
      - checkout
      # Build and run the tests
      - run:
          name: Build and run the tests
          command: |
            mvn clean compile test

# Invoke jobs via workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    jobs:
      - build-and-test